spring.application.name=farmer
spring.security.user.name=lakshmi
spring.security.user.password=lk
server.servlet.session.cookie.same-site=strict
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://localhost:3306/databas
spring.datasource.username = root
spring.datasource.password = Lakshmanan@02
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect